// Writes public/_redirects and public/robots.txt at build time, because both depend
// on env vars (Sanity project ID, site URL). Both files are git-ignored.
const fs = require("fs");
const path = require("path");
require("dotenv").config();

const projectId = process.env.NEXT_PUBLIC_STUDIO_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";
const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "").replace(/\/+$/, "");

// Sanity asset proxy: generatePageData rewrites cdn.sanity.io URLs to these paths on
// Netlify, so images/videos are served from our own domain. No other redirects.
const redirects = `# Generated by src/app/utils/generateNetlifyFiles.cjs — do not edit.
/sanity-images/*  https://cdn.sanity.io/images/${projectId}/${dataset}/:splat  200
/sanity-files/*   https://cdn.sanity.io/files/${projectId}/${dataset}/:splat  200
`;

const robots = `User-agent: *\nAllow: /\n\nSitemap: ${siteUrl}/sitemap.xml\n`;

const publicDir = path.join(process.cwd(), "public");
fs.writeFileSync(path.join(publicDir, "_redirects"), redirects);
fs.writeFileSync(path.join(publicDir, "robots.txt"), robots);
console.log("✅ _redirects + robots.txt generated.");
