// Writes public/sitemap.xml from the slugs generated by generateSlugs.cjs.
const fs = require("fs");
const path = require("path");
require("dotenv").config();

const BASE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "").replace(/\/+$/, "");

const slugs = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), "public/static-slugs.json"), "utf-8")
);

const urls = slugs.map((slug) => `  <url><loc>${BASE_URL}${slug === "/" ? "/" : `/${slug}`}</loc></url>`);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>
`;

fs.writeFileSync(path.join(process.cwd(), "public/sitemap.xml"), xml);
console.log(`✅ Sitemap generated (${urls.length} urls).`);
